const OWNER_KEY='botwawa_owner';
let owner=localStorage.getItem(OWNER_KEY);
if(!owner){owner=crypto.randomUUID?crypto.randomUUID():Math.random().toString(36).slice(2)+Date.now();localStorage.setItem(OWNER_KEY,owner)}
async function api(url,opt={}){const r=await fetch(url,{headers:{'Content-Type':'application/json','X-Bot-Owner':owner,...(opt.headers||{})},...opt});let x={};try{x=await r.json()}catch{}if(!r.ok&&!x.error)x.error='Request gagal';return x}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
async function createBot(){const name=document.getElementById('name').value.trim();const phone=document.getElementById('phone').value.trim();const out=document.getElementById('result');const btn=document.getElementById('create');if(!name||!phone){out.innerHTML='<span class="warn">Nama dan nomor wajib diisi.</span>';return}btn.disabled=true;out.innerHTML='<span class="muted">Menjalankan SC Tenka dan meminta pairing code asli...</span>';const x=await api('/api/sessions',{method:'POST',body:JSON.stringify({name,phone})});btn.disabled=false;if(x.error){out.innerHTML='<span class="warn">'+esc(x.error)+'</span>'}else{out.innerHTML='<span class="ok">Bot '+esc(x.id)+' sedang dijalankan.</span><div class="muted">Tunggu beberapa detik. Pairing code akan muncul otomatis saat SC Tenka mengeluarkannya.</div>';if(x.pairingCode)out.innerHTML+='<div class="code">'+esc(x.pairingCode)+'</div>'}setTimeout(load,1200)}
async function load(){const x=await api('/api/sessions');const el=document.getElementById('sessions');if(!x.sessions){el.innerHTML='<span class="warn">'+esc(x.error||'Gagal memuat bot')+'</span>';return}el.innerHTML=x.sessions.length?x.sessions.map(s=>`<div class="item"><b>${esc(s.name||s.id)}</b><div class="muted">${esc(s.phone||'-')} • <span class="${s.status==='online'?'ok':'warn'}">${esc(s.status)}</span></div>${s.pairingCode?`<div class="code">${esc(s.pairingCode)}</div>`:''}<div class="actions"><button onclick="act('${esc(s.id)}','start')">Start</button><button onclick="act('${esc(s.id)}','restart')">Restart</button><button onclick="act('${esc(s.id)}','stop')">Stop</button><button class="danger" onclick="delBot('${esc(s.id)}')">Hapus</button></div></div>`).join(''):'<div class="muted">Belum ada bot.</div>'}
async function act(id,a){await api('/api/sessions/'+encodeURIComponent(id)+'/'+a,{method:'POST',body:JSON.stringify({})});load()}
async function delBot(id){if(!confirm('Hapus bot '+id+' beserta session WhatsApp-nya?'))return;await api('/api/sessions/'+encodeURIComponent(id)+'/delete',{method:'POST'});load()}
load();setInterval(load,3000);
